// 경험 데이터 (constants/experience.ts)
import type { ExperienceItem } from '@/interfaces/experience.types';

export const EXPERIENCE: ExperienceItem[] = [
  {
    id: 'education-baekje-high-school',
    type: 'education',
    period: '2020.03 – 2023.02',
    category: 'EDUCATION',
    title: '백제고등학교',
    subtitle: '졸업',
    description: '고등학교 졸업',
    tags: [],
  },
  {
    id: 'education-hongik-university',
    type: 'education',
    period: '2023.03 – 2027.02',
    category: 'EDUCATION',
    title: '홍익대학교',
    subtitle: '소프트웨어융합학과 · 졸업 예정',
    description: '소프트웨어 개발, 웹 시스템, 데이터베이스, AI 관련 분야를 학습',
    tags: ['Software Engineering', 'Web', 'Database', 'AI'],
  },
  {
    id: 'activity-hongik-urop',
    type: 'activity',
    period: '2025.09 – 2025.12',
    category: 'CAMPUS ACTIVITY',
    title: '홍익대학교 UROP',
    subtitle: '2025년도 2학기',
    description: '학부 연구 프로그램에 참여하여 AI 기반 웹 탐색 및 테스트 관련 연구를 수행했습니다.',
    tags: [],
  },
  {
    id: 'activity-hongik-challenge',
    type: 'activity',
    period: '2025.09 – 2025.12',
    category: 'CAMPUS ACTIVITY',
    title: '홍익대학교 대학교육혁신사업단 · 홍익챌린지',
    subtitle: '',
    description: '교내 프로젝트 및 도전형 프로그램에 참여했습니다.',
    tags: [],
  },
  {
    id: 'activity-rise-scholarship',
    type: 'activity',
    period: '2026.07 – 2026.08',
    category: 'CAMPUS ACTIVITY',
    title: 'RISE 사업단 연구 장학생',
    subtitle: '',
    description: '연구 장학생으로 참여하여 연구 및 프로젝트 활동을 수행했습니다.',
    tags: [],
  },
  {
    id: 'research-se-lab',
    type: 'research',
    period: '2025.06 – Present',
    category: 'RESEARCH EXPERIENCE',
    title: 'SE Lab 학부연구생',
    subtitle: 'Undergraduate Researcher',
    description: 'AI 기반 웹 테스트와 소프트웨어 공학 관련 연구를 수행하고 있습니다.',
    tags: ['Software Engineering', 'AI Test Agent', 'Web Testing', 'Research'],
  },
];
